version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_list_backend
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    command: php artisan serve --host=0.0.0.0 --port=80
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_tasks
      MYSQL_USER: user_tasks
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local